name: Build & Deploy

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      python:
        image: python:latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.8"
          channel: "stable"

      - name: Enable desktop
        run: flutter config --enable-web
      
      - name: Build
        run: flutter build web

      - name: List directory
        run: |
          ls -al
      
